FROM maven:3.8.6-openjdk-11-slim as build

COPY src /home/app/src
COPY pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean install -DskipTests

FROM openjdk:11-jre-slim

COPY --from=build /home/app/target/config-server-0.0.1-SNAPSHOT.jar /usr/local/lib/config-server.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/config-server.jar"]
