spring:
  profiles:
    active: dev
---
eureka:
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: servicio-eureka
server:
  port: '8761'
