server:
  port: 8090

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/wpretell/BankSystem.git
          default-label: main
          search-paths: config-data

