server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/iqvan/bootcamp-cloud-config.git
          default-label: main
          search-paths: config-data
          username: iqvan
          password: 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
